spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://anjalisahualb:Anjalisahu123@quickserve.mcktoxs.mongodb.net/quickserveDB?retryWrites=true&w=majority&appName=QuickServe
spring.security.csrf.enabled=false
server.port=8080
# JWT Config
jwt.secret=YKiXwPrdRskniuHQTgKqj3ReWuRUp6HcHQNpC9rXFK1oDWEe3igbXKTrUmF5MiZM
jwt.expirationMs=86400000
# jwt.algorithm=HS256


logging.level.com.quickServe.backend=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Razorpay Configuration

# Payment Settings
# payment.currency=INR
# payment.timeout=900000



# razorpay.api.key=rzp_test_E1VHn4r8R09Rak
# razorpay.api.secret=6TLrS5L5z2YkBguOmXq3EIns


razorpay.key.id= rzp_test_Rl6SN5IR0FxoQt
razorpay.key.secret= TGf101mlLVZBKH85rFlJSKka

# Payment Configuration
payment.currency=INR
payment.timeout=900000